modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/fzzyhmstrs/sns/issues"
license = "TDL-M (https://github.com/fzzyhmstrs/Timefall-Development-Licence-Modified)"

[[mods]]
modId = "symbols_n_stuff"
version = "${version}"
displayName = "Symbols 'n' Stuff"
authors = "fzzyhmstrs"
description = '''
Simple utility mod that adds text-based symbols for spicing up your tooltips, screens, and more!
'''
logoFile = "assets/symbols_n_stuff/icon.png"

[[mixins]]
config = "symbols_n_stuff.mixins.json"

[[dependencies.symbols_n_stuff]]
modId = "neoforge"
type = "REQUIRED"
versionRange = "[21.0.0-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.symbols_n_stuff]]
modId = "minecraft"
type = "REQUIRED"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.symbols_n_stuff]]
modId = "kotlinforforge"
type = "REQUIRED"
versionRange = "[5.3.0,)"
ordering = "NONE"
side = "BOTH"